apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 0
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: node:20.12.1  # Cambia esta línea a la imagen que construyas con tu Dockerfile
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/authentication-service"
        - name: JWT_SECRET
          value: "your_jwt_secret"
        - name: JWT_EXPIRE
          value: "30d"
